[package]
name = "matrixon"
version = "0.11.0-alpha"
authors = ["arkSong <arksong2018@gmail.com>"]
edition = "2021"
description = "Ultra High Performance Matrix NextServer (Synapse Alternative)"
license = "Apache-2.0"
repository = "https://github.com/arkSong/Matrixon"
keywords = ["matrix", "chat", "federation", "server", "async"]
categories = ["network-programming", "web-programming"]

[[bin]]
name = "matrixon"
path = "src/main_fixed.rs"

[dependencies]
# Core async runtime
tokio = { version = "1.45", features = ["full"] }

# Web framework
axum = { version = "0.7", features = ["json", "headers", "query"] }
tower = { version = "0.5", features = ["full"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# HTTP
hyper = { version = "1.6", features = ["full"] }

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Development dependencies
[dev-dependencies]
tempfile = "3.8" 
