# Matrixon Simple Test Configuration
server_name = "localhost:6167"
address = "0.0.0.0"
port = 6167
database_url = "sqlite:matrixon_test.db"
allow_registration = true
allow_federation = true
allow_jaeger = false
tracing_flame = false
log = "info"
max_request_size = 67108864 
