#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Ask for the Matrix NextServer name, address and port.
db_input high matrix-matrixon/hostname || true
db_go

db_input low matrix-matrixon/address || true
db_go

db_input medium matrix-matrixon/port || true
db_go

exit 0
