[book]
description = "matrixon is a simple, fast and reliable chat server for the Matrix protocol"
language = "en"
multilingual = false
src = "docs"
title = "matrixon"

[build]
build-dir = "public"
create-missing = true

[output.html]
edit-url-template = "https://gitlab.com/famedly/matrixon/-/edit/next/{path}"
git-repository-icon = "fa-git-square"
git-repository-url = "https://gitlab.com/famedly/matrixon"

[output.html.search]
limit-results = 15

[output.html.code.hidelines]
json = "~"
