[global]
# The server_name is the pretty name of this server. It is used as a suffix for user
# and room ids. Examples: matrix.org, matrixon.rs
server_name = "localhost"

# Database backend - using PostgreSQL for enterprise deployment
database_backend = "postgresql"
database_path = "postgresql://zhiguangsong@localhost:5432/matrixon"

# The port Matrixon will be running on
port = 6167

# Max size for uploads (20MB)
max_request_size = 20_000_000

# Enables registration. If set to false, no users can register on this server.
allow_registration = true

# Allow federation with other Matrix servers
allow_federation = true

# Enable the display name lightning bolt on registration.
enable_lightning_bolt = true

# Servers listed here will be used to gather public keys of other servers.
trusted_servers = ["matrix.org"]

# Controls the log verbosity
log = "info"

# Bind address
address = "127.0.0.1"

# High performance settings for PostgreSQL
db_cache_capacity_mb = 1024.0
max_concurrent_requests = 1000
pdu_cache_capacity = 100000

# Well-known configuration for client discovery
[global.well_known]
client = "http://localhost:6167" 
